# Generated by Django 2.1 on 2018-08-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtquiz', '0002_auto_20180811_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answerable',
            field=models.BooleanField(default=False),
        ),
    ]
